apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-app
  namespace: feedback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-app
  template:
    metadata:
      labels:
        app: feedback-app
    spec:
      containers:
      - name: feedback-app
        image: <your_dockerhub_username>/feedback-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-app-service
  namespace: feedback
spec:
  selector:
    app: feedback-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
