apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-agent
  namespace: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-agent
  template:
    metadata:
      labels:
        app: model-agent
    spec:
      containers:
      - name: model-agent
        image: <your_dockerhub_username>/model-agent:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: model-agent-service
  namespace: model
spec:
  selector:
    app: model-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
